#!/bin/bash

# 中央厨房管理系统演示脚本

echo "=========================================="
echo "🏭 中央厨房餐饮加盟管理系统 - 功能演示"
echo "=========================================="
echo ""

echo "📋 系统功能概览："
echo "✅ 用户管理 (管理员、加盟商、店长、厨房管理员)"
echo "✅ 中央厨房管理 (库存、生产计划、质量控制)"
echo "✅ 门店管理 (加盟门店信息、运营监控)"
echo "✅ 订单管理 (订单处理、配送管理)"
echo "✅ 产品管理 (菜品信息、价格管理)"
echo "✅ 财务管理 (成本核算、利润分析)"
echo "✅ 报表统计 (数据分析、可视化报表)"
echo ""

echo "🔧 技术栈："
echo "• Spring Boot 3.2.0 + Java 17"
echo "• Spring Security + JWT认证"
echo "• Spring Data JPA + H2数据库"
echo "• Thymeleaf + Bootstrap 5前端"
echo "• Maven项目管理"
echo ""

echo "📁 项目结构："
echo "central-kitchen-management/"
echo "├── src/main/java/com/ckm/"
echo "│   ├── entity/          # 数据实体类"
echo "│   ├── repository/      # 数据访问层"
echo "│   ├── service/         # 业务逻辑层"
echo "│   ├── controller/      # 控制器层"
echo "│   ├── config/          # 配置类"
echo "│   └── security/        # 安全相关"
echo "├── src/main/resources/"
echo "│   ├── application.yml  # 应用配置"
echo "│   └── templates/       # 前端模板"
echo "└── pom.xml             # Maven配置"
echo ""

echo "🚀 启动方式："
echo "1. 安装Maven: brew install maven"
echo "2. 运行命令: cd central-kitchen-management && mvn spring-boot:run"
echo "3. 访问地址: http://localhost:8080"
echo "4. 默认账号: admin / admin123"
echo ""

echo "📊 核心业务流程："
echo ""
echo "🏭 中央厨房运营流程："
echo "1. 📦 产品管理 - 定义菜品信息、价格标准"
echo "2. 📋 库存管理 - 监控原材料，智能补货提醒"
echo "3. 🏭 生产计划 - 根据订单需求制定生产计划"
echo "4. ✅ 质量控制 - 生产过程质量检查"
echo "5. 🚚 配送管理 - 成品配送到各加盟门店"
echo ""
echo "🏪 加盟门店运营流程："
echo "1. 📝 订单接收 - 接收客户订单需求"
echo "2. 📦 厨房备货 - 从中央厨房获取成品"
echo "3. 🍽️ 门店销售 - 向客户提供服务"
echo "4. 📊 数据上报 - 上报销售数据和运营情况"
echo ""

echo "🔌 API接口示例："
echo ""
echo "# 用户认证"
echo "POST /api/auth/login     # 用户登录"
echo "POST /api/auth/register  # 用户注册"
echo ""
echo "# 厨房管理"
echo "GET  /api/kitchen/inventory              # 库存查询"
echo "POST /api/kitchen/production-plans       # 创建生产计划"
echo "GET  /api/kitchen/reports/inventory-value # 库存价值统计"
echo ""
echo "# 门店管理"
echo "GET  /api/store                         # 门店列表"
echo "POST /api/store                         # 创建门店"
echo ""

echo "💾 数据库配置："
echo "• 开发环境: H2内存数据库 (无需安装)"
echo "• 生产环境: MySQL 8.0"
echo "• 自动建表: Hibernate DDL-Auto"
echo ""

echo "🔒 安全特性："
echo "• JWT身份认证"
echo "• 角色-based权限控制"
echo "• RESTful API安全"
echo "• 密码加密存储"
echo ""

echo "📈 系统优势："
echo "✅ 中央厨房模式 - 标准化、规模化生产"
echo "✅ 智能化管理 - 库存预警、生产预测"
echo "✅ 数据驱动 - 完整的统计报表体系"
echo "✅ 易于扩展 - 模块化设计，支持多门店"
echo "✅ 用户友好 - 现代化Web界面"
echo ""

echo "🎯 适用场景："
echo "• 连锁餐饮企业 (麦当劳、肯德基等)"
echo "• 中央厨房配送企业"
echo "• 餐饮加盟连锁品牌"
echo "• 学校/企业食堂管理"
echo ""

echo "=========================================="
echo "✅ 系统演示完成！"
echo "=========================================="
